/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'contentUpdates': MotiaStream<unknown>
    'comments': MotiaStream<unknown>
  }

  interface Handlers {
    'ValidateContent': EventHandler<never, { topic: 'content.validated'; data: never }>
    'GenerateRecommendations': EventHandler<never, never>
    'GenerateImprovedContent': EventHandler<never, never>
    'AnalyzeWithAI': EventHandler<never, { topic: 'content.analyzed'; data: never }>
    'DailyProcessing': CronHandler<never>
    'VoteRecommendation': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'RequestContentImprovement': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'content.improvement.requested'; data: never }>
    'ListContent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetContent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetComments': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'DeleteContent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateContent': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'content.created'; data: never }>
    'ApplyImprovedContent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'AddComment': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}