/**
 * Shared TypeScript types for ContentFlow
 * 
 * This file defines the data contracts for content workflow,
 * AI analysis results, recommendations, and workflow status.
 */

/**
 * Input data structure for content submission
 */
export interface ContentInput {
  title: string;
  body: string;
  author: string;
  language: string;
  userId?: string; // Optional userId for user-specific filtering
}

/**
 * Content state stored in Motia state management
 */
export interface ContentState {
  contentId: string;
  title: string;
  body: string;
  author: string;
  language: string;
  userId?: string; // User ID for filtering content by user
  createdAt: string;
  updatedAt: string;
  workflowStatus: WorkflowStatus;
  validationResult?: ValidationResult;
  aiAnalysis?: AIAnalysisResult;
  recommendations?: Recommendation[];
  improvedContent?: ImprovedContent; // AI-generated improved version
}

/**
 * Workflow status tracking
 */
export type WorkflowStatus =
  | 'pending'        // Initial state, content created
  | 'validating'     // Validation in progress
  | 'validated'      // Validation passed
  | 'analyzing'      // AI analysis in progress
  | 'analyzed'       // AI analysis complete
  | 'completed'      // All steps complete
  | 'failed'         // Workflow failed at some step
  | 'rejected';      // Content rejected during validation

/**
 * Validation result from content validation step
 */
export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  validatedAt: string;
}

/**
 * AI analysis result from content analysis step
 */
export interface AIAnalysisResult {
  sentiment: 'positive' | 'neutral' | 'negative';
  topics: string[];
  readabilityScore: number;
  wordCount: number;
  qualityScore: number;
  summary: string;
  strengths: string[];
  weaknesses: string[];
  analyzedAt: string;
}

/**
 * Recommendation for content improvement or publishing
 */
export interface Recommendation {
  id: string;
  type: 'publish' | 'improve' | 'review' | 'optimize';
  title: string;
  description: string;
  priority: 'high' | 'medium' | 'low';
  actionableSteps: string[];
  votes?: {
    upvotes: number;
    downvotes: number;
    userVotes: Record<string, 'up' | 'down'>;
  };
}

/**
 * Comment on content analysis or recommendations
 */
export interface Comment {
  id: string;
  contentId: string;
  userId: string;
  userName: string;
  text: string;
  type: 'analysis' | 'recommendation' | 'general';
  targetId?: string; // ID of specific analysis or recommendation being commented on
  createdAt: string;
  updatedAt: string;
}

/**
 * Collaborative session for content
 */
export interface CollaborativeSession {
  contentId: string;
  participants: string[];
  activeViewers: number;
  lastActivity: string;
}

/**
 * Vote on a recommendation
 */
export interface Vote {
  contentId: string;
  recommendationId: string;
  userId: string;
  vote: 'up' | 'down';
  createdAt: string;
}

/**
 * Improved content generated by AI
 */
export interface ImprovedContent {
  originalBody: string; // Preserved original for comparison
  improvedBody: string;
  generatedAt: string;
  status: 'generating' | 'completed' | 'failed';
  appliedAt?: string;
}

